<?php

/**
 * CoComment integration
 * http://www.cocomment.com
 *
 * @author 
 *   Developed by Olaf Schettler
 *   Update to Drupal-5 by Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implementation of hook_menu().
 */
function cocomment_menu($may_cache) {
  if (!$may_cache) {
    //This is a workaround to reset $op to it's original value
    //that has been changed by cocomment's enabler.js and prevents
    //the comment submission
    if ($_POST['form_id'] == 'comment_form') {
      if ($_POST['op'] != t('Preview comment') AND $_POST['op'] != t('Post comment')) {
        $_POST['op'] = t('Post comment');
      }
    }
  }
}

/**
 * Implementation of hook_comment().
 */
function cocomment_comment($form, $op) {
  global $base_url, $user;

  if ($op == 'form' && $form['submit']) {
    //load necessary information
    $node = node_load($form['nid']['#value']);

    //prepare data for cocomment
    $coco = array(
      'tool'        => 'Drupal (+http://drupal.org/)',
      'siteurl'     => $base_url,
      'sitetitle'   => variable_get('site_name', $_SERVER['HTTP_HOST']),
      'pageurl'     => url('node/'. $node->nid, NULL, NULL, TRUE),
      'pagetitle'   => $node->title,
      'textareaID'  => 'comment',
      'buttonID'    => 'edit-submit',
      'author'      => $user->name ? $user->name : '',
      'authorID'    => 'name',
      'formID'      => 'comment-form',
    );
    //add data to site header
    drupal_add_js('coco = '. drupal_to_js($coco), 'inline');

    //add cocomment's enabler.js to the site
    $item['cocomment'] = array(
      '#value' => '<script type="text/javascript" id="cocomment-fetchlet" src="http://www.cocomment.com/js/enabler.js"></script>',
    );

    return $item;
  }
}
