<?php
// $Id$
/**
 * Module hooks
 */

function cocomment_help($section='') {
  switch ($section) {
    case 'admin/help#cocomment':

    case 'admin/modules#description':
      return t('Post comments to the coComment website.');
  }
}

/*
 * Callbacks
 */
function cocomment_comment($form, $op) {
  global $base_url, $user;

  $item = array();
  if ($op == 'form') {

    $site_title = variable_get('site_name', $_SERVER['HTTP_HOST']);

    $nid = $form['nid']['#value'];
    $node = node_load($nid);

    $node_title = addslashes($node->title);

    $item['submit'] = $form['submit'];
    $item['submit']['#attributes'] = array('id' => 'op_submit');

    $item['#prefix'] = <<<EOS
<script type="text/javascript">
var coco = {
  tool              : 'Drupal',
  siteurl           : '{$base_url}',
  sitetitle         : '{$site_title}',
  pageurl           : '{$base_url}{$form['#action']}',
  pagetitle         : '{$node_title}',

EOS;
    if (isset($form['author']['#value'])) {
      $item['#prefix'] .= "  author            : '{$form['author']['#value']}',\n";
    }
    else {
      $item['#prefix'] .= "  authorID          : 'edit[name]',\n";
    }
    $item['#prefix'] .= <<<EOS
  formID            : 'comment_form',
  textareaID        : 'edit[comment]',
  buttonID          : 'op_submit'
}
</script><script 
  type="text/javascript" id="cocomment-fetchlet" 
  src="http://www.cocomment.com/js/enabler.js"></script>
EOS;

    return $item;
  }
}
